### ISSUE TITLE
Trailing bytes trim too much

### ISSUE THREAD

**Issue by markfinn** [wd5gnr/scopesnap#1]
I was getting

> Reading data for pulse.png
convert-im6.q16: length and filesize do not match `/tmp/image11485.raw.bmp' @ error/bmp.c/ReadBMPImage/825.
convert-im6.q16: insufficient image data in file `/tmp/image11485.raw.bmp' @ error/bmp.c/ReadBMPImage/973.
convert-im6.q16: no images defined `pulse.png' @ error/convert.c/ConvertImageCommand/3258.
Error writing pulse.png

On my Rigol DS1104Z Plus 00.04.04.SP3 on Ubuntu 18.04.1.  It looks like my data is only trailed by 1 0x0a instead of the 3 bytes that you were expecting.  Not sure where the difference is, so I reworked the script to get the size from the BMP header.  Still assumes 11 bytes at beginning.

```
99,101c99,101
<   SIZE=`ls -l $FILE | cut -d ' ' -f 5`
<   SIZE=`expr $SIZE - 11`
<   tail -c $SIZE $FILE | head -c -3 >$BFILE
---
>   SIZE=`od -j 13 -N 4 -t u4 -An $FILE | tr -d '[:space:]'`
>   dd if=$FILE bs=1 skip=11 count=$SIZE >$BFILE
```

**Comment by markfinn** [comment]
Actually, this is better than my first fix, it uses the SCPI command size instead of assuming a BMP:
```
99,101c99,101
<   SIZE=`ls -l $FILE | cut -d ' ' -f 5`
<   SIZE=`expr $SIZE - 11`
<   tail -c $SIZE $FILE | head -c -3 >$BFILE
---
>   COUNTSIZE=$(cut $FILE -c 2)
>   SIZE=$(cut $FILE -c3-$((2+$COUNTSIZE)))
>   dd if=$FILE bs=1 skip=$((2+$COUNTSIZE)) count=$SIZE >$BFILE
```

**Comment by wd5gnr** [comment]
Oh I just noticed these. Thanks for looking into this.

**Comment by markfinn** [comment]
Thanks for the merge!
